version: 2
updates:
  # GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: ⬆
  # Python uv
  - package-ecosystem: uv
    directory: /backend
    schedule:
      interval: daily
    commit-message:
      prefix: ⬆
  # bun
  - package-ecosystem: bun
    directory: /expo
    schedule:
      interval: daily
    commit-message:
      prefix: ⬆
  # Docker
  - package-ecosystem: docker
    directories:
      - /backend
      - /expo
    schedule:
      interval: weekly
    commit-message:
      prefix: ⬆
  # Docker Compose
  - package-ecosystem: docker-compose
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: ⬆
